/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TkBookmarkAppExtensionRoot {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTkBookmarkAppExtensionRootElement extends Components.TkBookmarkAppExtensionRoot, HTMLStencilElement {
    }
    var HTMLTkBookmarkAppExtensionRootElement: {
        prototype: HTMLTkBookmarkAppExtensionRootElement;
        new (): HTMLTkBookmarkAppExtensionRootElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "tk-bookmark-app-extension-root": HTMLTkBookmarkAppExtensionRootElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TkBookmarkAppExtensionRoot {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "tk-bookmark-app-extension-root": TkBookmarkAppExtensionRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "tk-bookmark-app-extension-root": LocalJSX.TkBookmarkAppExtensionRoot & JSXBase.HTMLAttributes<HTMLTkBookmarkAppExtensionRootElement>;
        }
    }
}
